### PR TITLE
Progress indicator and audio 

### PR DESCRIPTION
**Pull request by shilangyu**
Implemented #34  & #50

### CODE REVIEW

**Comment by shilangyu** [comment]
Sorry for a separate PR, forgot to include it in the previous one :/

**Comment by ArneVogel** [comment]
No problem, are you going to tackle more issues/features or should I merge and create a new release?

**Comment by shilangyu** [comment]
Was thinking about #50 however I'm not familiar with the twitch API (so I don't know if it's possible to download audio directly), the only thing I can think of is downloading the chunks and just extracting the audio at the end (seems bandwidth heavy for an audio only download tho)

**Comment by ArneVogel** [comment]
Yes, last time I checked there was no way to download only the audio from a vod. So the only way to give a audio only option would be to convert the video with ffmpeg.

**Comment by shilangyu** [comment]
Would that be an acceptable implementation? I can code that and add in the Readme that in fact it's downloading the whole vod either way so it won't save any bandwidth

**Comment by ArneVogel** [comment]
Yes, I think that implementation would still be a benefit for people who dont have any experience with ffmpeg, even when it doesnt save bandwidth. 
I think two options for audio downloads would be good. One `-audio-only` where only the audio file is kept and one `-audio` where both the normal video (not muted) and the audio file is kept.

**Comment by shilangyu** [comment]
Done! :)

**Pull request merged**
