### PR TITLE
Issue features

### PR DESCRIPTION
**Pull request by shilangyu**
- added download path flag `-download-path` (part of #43)
- `ffmpeg` is not checked if `-qualityinfo` flag is passed (#32)

- [x] #43 
- [x] #32 
- [x] #33 
- [x] #46

### CODE REVIEW

**Comment by shilangyu** [comment]
i plan on fixing #46 and #33 aswell.

**Comment by ArneVogel** [comment]
Ok, let me know when I should merge.

**Comment by shilangyu** [comment]
#46 complete

**Comment by shilangyu** [comment]
I think im done, please check and let me know if its ok. I fixed/implemented 4 issues listed above

**Comment by ArneVogel** [comment]
Thank you very much for your work. I created a new release with your changes: https://github.com/ArneVogel/concat/releases/tag/v0.2.6

**Pull request merged**
